spring:
  # config.activate.on-profile: dev
  datasource:
    # url: jdbc:mysql://localhost:3306
    url: jdbc:mariadb://localhost:3306
    username: admin
    password: 1234
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
      hibernate:
        ddl-auto: update

server:
  port: 1004

# ---

# spring:
#   config.activate.on-profile: dev
#   datasource:
#     url: jdbc:mysql://localhost:3306/mydb_dev?characterEncoding=UTF-8
#     driverClassName: com.mysql.cj.jdbc.Driver
#     username: admin
#     password: 1234
#   jpa:
#     hibernate:
#       ddl-auto: update
#   servlet:
#     multipart:
#       max-file-size: -1
#       max-request-size: -1

# cms:
#   storage:
#     update: D:/data/update/
#     path: D:/data/storage/

# server:
#   port: 9898

